// Mapping of continents to country codes (ISO 3166-1 alpha-2)

export type CountryInfo = {
  code: string;
  name: string;
  capital: string;
};

export type Continents = {
  [continent: string]: CountryInfo[];
};

const continents: Continents = {
  Africa: [
    { code: 'dz', name: 'Algeria', capital: 'Algiers' },
    { code: 'ao', name: 'Angola', capital: 'Luanda' },
    { code: 'bj', name: 'Benin', capital: 'Porto-Novo' },
    { code: 'bw', name: 'Botswana', capital: 'Gaborone' },
    { code: 'bf', name: 'Burkina Faso', capital: 'Ouagadougou' },
    { code: 'bi', name: 'Burundi', capital: 'Gitega' },
    { code: 'cm', name: 'Cameroon', capital: 'Yaoundé' },
    { code: 'cv', name: 'Cape Verde', capital: 'Praia' },
    { code: 'cf', name: 'Central African Republic', capital: 'Bangui' },
    {
      code: 'td', name: 'Chad', capital: `N'Djamena`
    },
    { code: 'km', name: 'Comoros', capital: 'Moroni' },
    { code: 'cg', name: 'Republic of the Congo', capital: 'Brazzaville' },
    { code: 'cd', name: 'Democratic Republic of the Congo', capital: 'Kinshasa' },
    { code: 'ci', name: 'Ivory Coast', capital: 'Yamoussoukro' },
    { code: 'dj', name: 'Djibouti', capital: 'Djibouti' },
    { code: 'eg', name: 'Egypt', capital: 'Cairo' },
    { code: 'gq', name: 'Equatorial Guinea', capital: 'Malabo' },
    { code: 'er', name: 'Eritrea', capital: 'Asmara' },
    { code: 'sz', name: 'Eswatini', capital: 'Mbabane' },
    { code: 'et', name: 'Ethiopia', capital: 'Addis Ababa' },
    { code: 'ga', name: 'Gabon', capital: 'Libreville' },
    { code: 'gm', name: 'Gambia', capital: 'Banjul' },
    { code: 'gh', name: 'Ghana', capital: 'Accra' },
    { code: 'gn', name: 'Guinea', capital: 'Conakry' },
    { code: 'gw', name: 'Guinea-Bissau', capital: 'Bissau' },
    { code: 'ke', name: 'Kenya', capital: 'Nairobi' },
    { code: 'ls', name: 'Lesotho', capital: 'Maseru' },
    { code: 'lr', name: 'Liberia', capital: 'Monrovia' },
    { code: 'ly', name: 'Libya', capital: 'Tripoli' },
    { code: 'mg', name: 'Madagascar', capital: 'Antananarivo' },
    { code: 'mw', name: 'Malawi', capital: 'Lilongwe' },
    { code: 'ml', name: 'Mali', capital: 'Bamako' },
    { code: 'mr', name: 'Mauritania', capital: 'Nouakchott' },
    { code: 'mu', name: 'Mauritius', capital: 'Port Louis' },
    { code: 'yt', name: 'Mayotte', capital: 'Mamoudzou' },
    { code: 'ma', name: 'Morocco', capital: 'Rabat' },
    { code: 'mz', name: 'Mozambique', capital: 'Maputo' },
    { code: 'na', name: 'Namibia', capital: 'Windhoek' },
    { code: 'ne', name: 'Niger', capital: 'Niamey' },
    { code: 'ng', name: 'Nigeria', capital: 'Abuja' },
    { code: 'rw', name: 'Rwanda', capital: 'Kigali' },
    { code: 're', name: 'Réunion', capital: 'Saint-Denis' },
    { code: 'sh', name: 'Saint Helena', capital: 'Jamestown' },
    { code: 'st', name: 'São Tomé and Príncipe', capital: 'São Tomé' },
    { code: 'sn', name: 'Senegal', capital: 'Dakar' },
    { code: 'sc', name: 'Seychelles', capital: 'Victoria' },
    { code: 'sl', name: 'Sierra Leone', capital: 'Freetown' },
    { code: 'so', name: 'Somalia', capital: 'Mogadishu' },
    { code: 'za', name: 'South Africa', capital: 'Pretoria' },
    { code: 'ss', name: 'South Sudan', capital: 'Juba' },
    { code: 'sd', name: 'Sudan', capital: 'Khartoum' },
    { code: 'tz', name: 'Tanzania', capital: 'Dodoma' },
    { code: 'tg', name: 'Togo', capital: 'Lomé' },
    { code: 'tn', name: 'Tunisia', capital: 'Tunis' },
    { code: 'ug', name: 'Uganda', capital: 'Kampala' },
    { code: 'eh', name: 'Western Sahara', capital: 'El Aaiún' },
    { code: 'zm', name: 'Zambia', capital: 'Lusaka' },
    { code: 'zw', name: 'Zimbabwe', capital: 'Harare' }
  ],
  Asia: [
    { code: 'af', name: 'Afghanistan', capital: 'Kabul' },
    { code: 'am', name: 'Armenia', capital: 'Yerevan' },
    { code: 'az', name: 'Azerbaijan', capital: 'Baku' },
    { code: 'bh', name: 'Bahrain', capital: 'Manama' },
    { code: 'bd', name: 'Bangladesh', capital: 'Dhaka' },
    { code: 'bt', name: 'Bhutan', capital: 'Thimphu' },
    { code: 'bn', name: 'Brunei', capital: 'Bandar Seri Begawan' },
    { code: 'mm', name: 'Myanmar', capital: 'Naypyidaw' },
    { code: 'kh', name: 'Cambodia', capital: 'Phnom Penh' },
    { code: 'cn', name: 'China', capital: 'Beijing' },
    { code: 'cx', name: 'Christmas Island', capital: 'Flying Fish Cove' },
    { code: 'cc', name: 'Cocos (Keeling) Islands', capital: 'West Island' },
    { code: 'ge', name: 'Georgia', capital: 'Tbilisi' },
    { code: 'hk', name: 'Hong Kong', capital: 'Hong Kong' },
    { code: 'in', name: 'India', capital: 'New Delhi' },
    { code: 'id', name: 'Indonesia', capital: 'Jakarta' },
    { code: 'ir', name: 'Iran', capital: 'Tehran' },
    { code: 'iq', name: 'Iraq', capital: 'Baghdad' },
    { code: 'il', name: 'Israel', capital: 'Jerusalem' },
    { code: 'jp', name: 'Japan', capital: 'Tokyo' },
    { code: 'jo', name: 'Jordan', capital: 'Amman' },
    { code: 'kz', name: 'Kazakhstan', capital: 'Astana' },
    { code: 'kp', name: 'North Korea', capital: 'Pyongyang' },
    { code: 'kr', name: 'South Korea', capital: 'Seoul' },
    { code: 'kw', name: 'Kuwait', capital: 'Kuwait City' },
    { code: 'kg', name: 'Kyrgyzstan', capital: 'Bishkek' },
    { code: 'la', name: 'Laos', capital: 'Vientiane' },
    { code: 'lb', name: 'Lebanon', capital: 'Beirut' },
    { code: 'mo', name: 'Macau', capital: 'Macau' },
    { code: 'my', name: 'Malaysia', capital: 'Kuala Lumpur' },
    { code: 'mv', name: 'Maldives', capital: 'Malé' },
    { code: 'mn', name: 'Mongolia', capital: 'Ulaanbaatar' },
    { code: 'np', name: 'Nepal', capital: 'Kathmandu' },
    { code: 'om', name: 'Oman', capital: 'Muscat' },
    { code: 'pk', name: 'Pakistan', capital: 'Islamabad' },
    { code: 'ps', name: 'Palestine', capital: 'Ramallah' },
    { code: 'ph', name: 'Philippines', capital: 'Manila' },
    { code: 'qa', name: 'Qatar', capital: 'Doha' },
    { code: 'sa', name: 'Saudi Arabia', capital: 'Riyadh' },
    { code: 'sg', name: 'Singapore', capital: 'Singapore' },
    { code: 'lk', name: 'Sri Lanka', capital: 'Sri Jayawardenepura Kotte' },
    { code: 'sy', name: 'Syria', capital: 'Damascus' },
    { code: 'tw', name: 'Taiwan', capital: 'Taipei' },
    { code: 'tj', name: 'Tajikistan', capital: 'Dushanbe' },
    { code: 'th', name: 'Thailand', capital: 'Bangkok' },
    { code: 'tl', name: 'Timor-Leste', capital: 'Dili' },
    { code: 'tr', name: 'Turkey', capital: 'Ankara' },
    { code: 'tm', name: 'Turkmenistan', capital: 'Ashgabat' },
    { code: 'ae', name: 'United Arab Emirates', capital: 'Abu Dhabi' },
    { code: 'uz', name: 'Uzbekistan', capital: 'Tashkent' },
    { code: 'vn', name: 'Vietnam', capital: 'Hanoi' },
    { code: 'ye', name: 'Yemen', capital: `Sana'a` }
  ],
  Europe: [
    { code: 'al', name: 'Albania', capital: 'Tirana' },
    { code: 'ad', name: 'Andorra', capital: 'Andorra la Vella' },
    { code: 'at', name: 'Austria', capital: 'Vienna' },
    { code: 'by', name: 'Belarus', capital: 'Minsk' },
    { code: 'be', name: 'Belgium', capital: 'Brussels' },
    { code: 'ba', name: 'Bosnia and Herzegovina', capital: 'Sarajevo' },
    { code: 'bg', name: 'Bulgaria', capital: 'Sofia' },
    { code: 'hr', name: 'Croatia', capital: 'Zagreb' },
    { code: 'cy', name: 'Cyprus', capital: 'Nicosia' },
    { code: 'cz', name: 'Czech Republic', capital: 'Prague' },
    { code: 'dk', name: 'Denmark', capital: 'Copenhagen' },
    { code: 'ee', name: 'Estonia', capital: 'Tallinn' },
    { code: 'fo', name: 'Faroe Islands', capital: 'Tórshavn' },
    { code: 'fi', name: 'Finland', capital: 'Helsinki' },
    { code: 'fr', name: 'France', capital: 'Paris' },
    { code: 'de', name: 'Germany', capital: 'Berlin' },
    { code: 'gi', name: 'Gibraltar', capital: 'Gibraltar' },
    { code: 'gr', name: 'Greece', capital: 'Athens' },
    { code: 'va', name: 'Vatican City', capital: 'Vatican City' },
    { code: 'hu', name: 'Hungary', capital: 'Budapest' },
    { code: 'is', name: 'Iceland', capital: 'Reykjavik' },
    { code: 'ie', name: 'Ireland', capital: 'Dublin' },
    { code: 'it', name: 'Italy', capital: 'Rome' },
    { code: 'lv', name: 'Latvia', capital: 'Riga' },
    { code: 'li', name: 'Liechtenstein', capital: 'Vaduz' },
    { code: 'lt', name: 'Lithuania', capital: 'Vilnius' },
    { code: 'lu', name: 'Luxembourg', capital: 'Luxembourg' },
    { code: 'mt', name: 'Malta', capital: 'Valletta' },
    { code: 'md', name: 'Moldova', capital: 'Chișinău' },
    { code: 'mc', name: 'Monaco', capital: 'Monaco' },
    { code: 'me', name: 'Montenegro', capital: 'Podgorica' },
    { code: 'nl', name: 'Netherlands', capital: 'Amsterdam' },
    { code: 'mk', name: 'North Macedonia', capital: 'Skopje' },
    { code: 'no', name: 'Norway', capital: 'Oslo' },
    { code: 'pl', name: 'Poland', capital: 'Warsaw' },
    { code: 'pt', name: 'Portugal', capital: 'Lisbon' },
    { code: 'ro', name: 'Romania', capital: 'Bucharest' },
    { code: 'ru', name: 'Russia', capital: 'Moscow' },
    { code: 'sm', name: 'San Marino', capital: 'San Marino' },
    { code: 'rs', name: 'Serbia', capital: 'Belgrade' },
    { code: 'sk', name: 'Slovakia', capital: 'Bratislava' },
    { code: 'si', name: 'Slovenia', capital: 'Ljubljana' },
    { code: 'es', name: 'Spain', capital: 'Madrid' },
    { code: 'sj', name: 'Svalbard and Jan Mayen', capital: 'Longyearbyen' },
    { code: 'se', name: 'Sweden', capital: 'Stockholm' },
    { code: 'ch', name: 'Switzerland', capital: 'Bern' },
    { code: 'ua', name: 'Ukraine', capital: 'Kyiv' },
    { code: 'gb', name: 'United Kingdom', capital: 'London' }
  ],
  NorthAmerica: [
    { code: 'ag', name: 'Antigua and Barbuda', capital: 'Saint John’s' },
    { code: 'bs', name: 'Bahamas', capital: 'Nassau' },
    { code: 'bb', name: 'Barbados', capital: 'Bridgetown' },
    { code: 'bz', name: 'Belize', capital: 'Belmopan' },
    { code: 'ca', name: 'Canada', capital: 'Ottawa' },
    { code: 'cr', name: 'Costa Rica', capital: 'San José' },
    { code: 'cu', name: 'Cuba', capital: 'Havana' },
    { code: 'dm', name: 'Dominica', capital: 'Roseau' },
    { code: 'do', name: 'Dominican Republic', capital: 'Santo Domingo' },
    { code: 'sv', name: 'El Salvador', capital: 'San Salvador' },
    { code: 'gd', name: 'Grenada', capital: 'St. George’s' },
    { code: 'gt', name: 'Guatemala', capital: 'Guatemala City' },
    { code: 'ht', name: 'Haiti', capital: 'Port-au-Prince' },
    { code: 'hn', name: 'Honduras', capital: 'Tegucigalpa' },
    { code: 'jm', name: 'Jamaica', capital: 'Kingston' },
    { code: 'mx', name: 'Mexico', capital: 'Mexico City' },
    { code: 'ni', name: 'Nicaragua', capital: 'Managua' },
    { code: 'pa', name: 'Panama', capital: 'Panama City' },
    { code: 'kn', name: 'Saint Kitts and Nevis', capital: 'Basseterre' },
    { code: 'lc', name: 'Saint Lucia', capital: 'Castries' },
    { code: 'vc', name: 'Saint Vincent and the Grenadines', capital: 'Kingstown' },
    { code: 'tt', name: 'Trinidad and Tobago', capital: 'Port of Spain' },
    { code: 'us', name: 'United States', capital: 'Washington, D.C.' }
  ],
  SouthAmerica: [
    { code: 'ar', name: 'Argentina', capital: 'Buenos Aires' },
    { code: 'bo', name: 'Bolivia', capital: 'Sucre' },
    { code: 'br', name: 'Brazil', capital: 'Brasília' },
    { code: 'cl', name: 'Chile', capital: 'Santiago' },
    { code: 'co', name: 'Colombia', capital: 'Bogotá' },
    { code: 'ec', name: 'Ecuador', capital: 'Quito' },
    { code: 'fk', name: 'Falkland Islands', capital: 'Stanley' },
    { code: 'gf', name: 'French Guiana', capital: 'Cayenne' },
    { code: 'gy', name: 'Guyana', capital: 'Georgetown' },
    { code: 'py', name: 'Paraguay', capital: 'Asunción' },
    { code: 'pe', name: 'Peru', capital: 'Lima' },
    { code: 'sr', name: 'Suriname', capital: 'Paramaribo' },
    { code: 'uy', name: 'Uruguay', capital: 'Montevideo' },
    { code: 've', name: 'Venezuela', capital: 'Caracas' }
  ],
  Oceania: [
    { code: 'as', name: 'American Samoa', capital: 'Pago Pago' },
    { code: 'au', name: 'Australia', capital: 'Canberra' },
    { code: 'ck', name: 'Cook Islands', capital: 'Avarua' },
    { code: 'fj', name: 'Fiji', capital: 'Suva' },
    { code: 'pf', name: 'French Polynesia', capital: 'Papeete' },
    { code: 'gu', name: 'Guam', capital: 'Hagåtña' },
    { code: 'ki', name: 'Kiribati', capital: 'South Tarawa' },
    { code: 'mh', name: 'Marshall Islands', capital: 'Majuro' },
    { code: 'fm', name: 'Micronesia', capital: 'Palikir' },
    { code: 'nr', name: 'Nauru', capital: 'Yaren' },
    { code: 'nc', name: 'New Caledonia', capital: 'Nouméa' },
    { code: 'nz', name: 'New Zealand', capital: 'Wellington' },
    { code: 'nu', name: 'Niue', capital: 'Alofi' },
    { code: 'nf', name: 'Norfolk Island', capital: 'Kingston' },
    { code: 'mp', name: 'Northern Mariana Islands', capital: 'Saipan' },
    { code: 'pw', name: 'Palau', capital: 'Ngerulmud' },
    { code: 'pg', name: 'Papua New Guinea', capital: 'Port Moresby' },
    { code: 'pn', name: 'Pitcairn Islands', capital: 'Adamstown' },
    { code: 'ws', name: 'Samoa', capital: 'Apia' },
    { code: 'sb', name: 'Solomon Islands', capital: 'Honiara' },
    { code: 'tk', name: 'Tokelau', capital: 'Fakaofo' },
    { code: 'to', name: 'Tonga', capital: 'Nukuʻalofa' },
    { code: 'tv', name: 'Tuvalu', capital: 'Funafuti' },
    { code: 'vu', name: 'Vanuatu', capital: 'Port Vila' },
    { code: 'wf', name: 'Wallis and Futuna', capital: 'Mata-Utu' }
  ],
  Antarctica: [
    { code: 'aq', name: 'Antarctica', capital: '' },
    { code: 'bv', name: 'Bouvet Island', capital: '' },
    { code: 'gs', name: 'South Georgia and the South Sandwich Islands', capital: 'King Edward Point' },
    { code: 'hm', name: 'Heard Island and McDonald Islands', capital: '' },
    { code: 'tf', name: 'French Southern and Antarctic Lands', capital: 'Port-aux-Français' }
  ]
}

export default continents;
